sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sisyphus/docker-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true sisyphus/docker-frontend npm run test --coverage
